dataset:
  name: pl
  path: ./data/crossdocked_pocket10
  split: ./data/split_by_name.pt

model:
  checkpoint: ./pretrained/model.pt
  hidden_channels: 256
  random_alpha: True

sample:
  seed: 2022
  num_samples: 100
  beam_size: 300
  logp_thres: -.inf
  num_retry: 5
  max_steps: 12
  batch_size: 10
  num_workers: 4
